# example values
spring:
  datasource:
    username: username
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
